services:
  - type: web
    name: akashic-server
    env: node
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: akashic-db
          property: connectionString
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: akashic-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://akashic-server.onrender.com

databases:
  - name: akashic-db
    plan: starter
    postDeploy: |
      psql $DATABASE_URL -f db/schema.sql
      psql $DATABASE_URL -f db/init.sql
